package com.example.ui

object LocalizedStrings {
    fun get(key: String, isArabic: Boolean): String {
        return if (isArabic) {
            when (key) {
                // Main & Navigator
                "quick_navigation" -> "انتقال سريع"
                "close" -> "إغلاق"
                "app_title" -> "حصّالة - مدير فلوسك المالي"
                
                // Tabs
                "tab_overview" -> "نظرة عامة"
                "tab_income" -> "القبض والدخل"
                "tab_expenses" -> "مصاريفك"
                "tab_bills" -> "فواتير واشتراكات"
                "tab_goals" -> "حصّالتك وأهدافك"
                "tab_calendar" -> "النتيجة والتقويم"
                "tab_search" -> "البحث والفلترة"
                "tab_settings" -> "الإعدادات"
                
                // Overview Screen
                "net_balance" -> "صافي فلوسك (رصيدك الحالي)"
                "income_cap" -> "دخل وارد"
                "expenses_cap" -> "مصاريف"
                "bills_cap" -> "فواتير"
                "financial_health" -> "معدل صحتك المالية"
                "excellent_health" -> "ممتاز! مصاريفك متظبطة ع الآخر"
                "moderate_health" -> "جيد! ماشي حالك بس محتاج شوية حذر"
                "needs_attention" -> "فوق لنفسك! مصاريفك عالية ومحتاج مراجعة"
                "net_worth" -> "ثروتك وصافي فلوسك"
                "assets" -> "➕ اللي ليك (دخل وادخار)"
                "liabilities" -> "➖ اللي عليك (مصاريف وفواتير)"
                "spending_breakdown" -> "تحليل نسب الصرف الشهري"
                "top_spending_in" -> "أكتر فئة صرفت عليها: "
                "gemini_advisor" -> "المستشار الذكي (Gemini AI)"
                "gemini_refresh" -> "تحديث النصائح الذكية"
                "gemini_default_insight" -> "اضغط على زرار التحديث فوق عشان الذكاء الاصطناعي يحلل مصاريفك ويديك نصايح ذهبية تظبط بيها ميزانيتك!"
                
                // Income Screen
                "total_income_this_month" -> "إجمالي الفلوس اللي دخلت الشهر ده"
                "sources_logged" -> "مورد دخل مسجل"
                "transactions" -> "المعاملات المالية"
                "no_income_yet" -> "مفيش أي دخل اتسجل لحد دلوقتي!"
                "add_income_instruction" -> "اضغط على علامة الـ + عشان تضيف أول دخل أو مرتب ليك!"
                
                // Expenses Screen
                "total_expenses_this_month" -> "إجمالي اللي صرفته الشهر ده"
                "total_transactions_logged" -> "معاملة صرف مسجلة"
                "by_category" -> "فلترة بحسب الفئات"
                "no_expenses_yet" -> "مفيش أي مصاريف اتسجلت الشهر ده!"
                "add_expense_instruction" -> "اضغط على زرار الـ + عشان تضيف أول بند صرف أو مصروف!"
                
                // Bills Screen
                "total_monthly" -> "مجموع الفواتير الشهري"
                "paid_this_month" -> "اللي دفعته الشهر ده"
                "all_recurring_bills" -> "كل فواتيرك واشتراكاتك المتكررة"
                "paid" -> "تم الدفع"
                "unpaid" -> "انتظار / لسه مدفعتش"
                "due_day" -> "يوم الدفع"
                "no_bills_yet" -> "مفيش أي فواتير مسجلة لحد دلوقتي!"
                "add_bill_instruction" -> "اضغط على علامة الـ + عشان تسجل فواتيرك أو اشتراكاتك الشهرية (نت، كهربا وغيرها)!"
                
                // Calendar
                "prev_month" -> "الشهر اللي فات"
                "next_month" -> "الشهر اللي جاي"
                "selected_date_details" -> "تفاصيل اليوم المختار"
                "no_transactions_today" -> "مفيش أي حركة مالية اتسجلت في اليوم ده."
                
                // Goals
                "saved_of_target" -> "محوش من هدفك"
                "add_funds_title" -> "تغذية حصالة هدفك"
                "amount_to_add" -> "المبلغ اللي عايز تضيفه للحصالة"
                "add_funds_btn" -> "زود في الحصالة"
                "cancel" -> "إلغاء وعودة"
                "no_goals_yet" -> "لسه معملتش أي هدف ادخار لحد دلوقتي!"
                "add_goal_instruction" -> "اضبط أهدافك المالية (زي تشتري لابتوب، تسافر...) وابدأ حوش ليهم!"
                "saved_of" -> "محوش من"
                
                // Settings Screen
                "appearance" -> "مظهر وتصميم التطبيق"
                "dark_light_theme" -> "الوضع (فاتح/غمق)"
                "language_currency" -> "الترجمة والعملة المستهدفة"
                "monthly_limit" -> "ميزانيتك القصوى في الشهر"
                "limit_not_set" -> "الحد الشهري مش مضبوط"
                "set_limit" -> "اضبط الحد الشهري"
                "custom_categories" -> "تعديل وإضافة بنود المصاريف"
                "add_custom_cat" -> "إضافة فئة جديدة"
                "cat_name" -> "اسم الفئة"
                "color_selection" -> "اختر لون مميز للفئة"
                "export_backup" -> "نسخ البيانات والاحتفاظ بها"
                "export_csv" -> "تصدير البيانات لملف CSV"
                "import_csv" -> "استيراد البيانات لملف CSV"
                "clear_data" -> "مسح كل البيانات والبدء من جديد"
                "clear_data_prompt" -> "عايز تمسح كل البيانات بجد؟"
                "clear_data_exp" -> "الإجراء ده هيمسح كل المدخلات والمصاريف والفواتير والأهداف من تليفونك ومفيش طريقة نرجعها تاني. متأكد؟"
                "clear_data_confirm" -> "أيوا، امسح كل حاجة"
                "save" -> "حفظ"
                
                // Dialog & Forms labels
                "edit_income" -> "تعديل بند الدخل"
                "add_income" -> "إضافة دخل جديد"
                "edit_expense" -> "تعديل بند المصروف"
                "add_expense" -> "إضافة مصروف جديد"
                "edit_bill" -> "تعديل الفاتورة"
                "add_bill" -> "إضافة فاتورة متكررة"
                "add_goal" -> "إضافة هدف ادخار جديد"
                "name" -> "وصف أو اسم البند (مثال: قبض الشغل)"
                "amount" -> "المبلغ"
                "category" -> "اختر الفئة المناسبة"
                "date" -> "تاريخ ووقت العملية (YYYY-MM-DD)"
                "notes_optional" -> "ملاحظات إضافية (اختياري)"
                "recurring_monthly" -> "يتكرر شهرياً بشكل تلقائي"
                "frequency" -> "معدل التكرار الدوري"
                "due_day_month" -> "يوم الاستحقاق من الشهر (رقم اليوم)"
                "pick_color_theme" -> "اختر لوناً مميزاً لحصالتك"
                "pick_logo_icon" -> "اختر رمزاً مناسباً"
                "goal_name" -> "اسم الهدف (مثال: كاش للطوارئ، لابتوب)"
                "target_amount" -> "المبلغ الإجمالي المستهدف"
                "deadline" -> "تاريخ انتهاء مستهدف (اختياري YYYY-MM-DD)"
                "saved_amount_status" -> "تم تجميع %s من إجمالي %s"
                "log_savable_amount" -> "المبلغ اللي عايز تضيفه للحصالة دلوقتي"
                "add_savings_btn" -> "ادخر في الحصالة"
                "streak_days" -> "أيام حماسك متتالية"
                "streak_count" -> "يوم"
                
                else -> key
            }
        } else {
            when (key) {
                "quick_navigation" -> "Quick Navigation"
                "close" -> "Close"
                "app_title" -> "Finance Tracker"
                "tab_overview" -> "Overview"
                "tab_income" -> "Income"
                "tab_expenses" -> "Expenses"
                "tab_bills" -> "Bills"
                "tab_goals" -> "Saving Goals"
                "tab_calendar" -> "Calendar"
                "tab_search" -> "Search & Filter"
                "tab_settings" -> "Settings"
                "net_balance" -> "Net Balance"
                "income_cap" -> "INCOME"
                "expenses_cap" -> "EXPENSES"
                "bills_cap" -> "BILLS"
                "financial_health" -> "Financial Health Score"
                "excellent_health" -> "Excellent Health - Perfect!"
                "moderate_health" -> "Moderate Control - Stable"
                "needs_attention" -> "Needs Attention - Overspending"
                "net_worth" -> "Net Worth"
                "assets" -> "➕ Assets"
                "liabilities" -> "➖ Liabilities"
                "spending_breakdown" -> "Spending Breakdown"
                "top_spending_in" -> "Top spending in: "
                "gemini_advisor" -> "Gemini Financial Advisor"
                "gemini_refresh" -> "Refresh Insights"
                "gemini_default_insight" -> "Click refresh on top to receive a real-time smart budget insight and investment suggestions from Google Gemini API!"
                "total_income_this_month" -> "TOTAL INCOME THIS MONTH"
                "sources_logged" -> "sources logged"
                "transactions" -> "Transactions"
                "no_income_yet" -> "No incomes logged yet."
                "add_income_instruction" -> "Click the + button to add your first income transaction."
                "total_expenses_this_month" -> "TOTAL EXPENSES THIS MONTH"
                "total_transactions_logged" -> "total transactions logged"
                "by_category" -> "By Category"
                "no_expenses_yet" -> "No expenses logged yet."
                "add_expense_instruction" -> "Click the + button to add your first expense transaction."
                "total_monthly" -> "TOTAL MONTHLY"
                "paid_this_month" -> "PAID THIS MONTH"
                "all_recurring_bills" -> "All Recurring Scheduled Bills"
                "paid" -> "Paid"
                "unpaid" -> "Unpaid"
                "due_day" -> "Due Day"
                "no_bills_yet" -> "No bills logged yet."
                "add_bill_instruction" -> "Click the + button below to log your monthly recurring scheduled payments."
                "prev_month" -> "Previous Month"
                "next_month" -> "Next Month"
                "selected_date_details" -> "Selected date details"
                "no_transactions_today" -> "No transactions logged on this day"
                "saved_of_target" -> "saved of target"
                "add_funds_title" -> "Add savings target funds"
                "amount_to_add" -> "Amount to add"
                "add_funds_btn" -> "Add Funds"
                "cancel" -> "Cancel"
                "no_goals_yet" -> "No saving goals created yet."
                "add_goal_instruction" -> "Establish your financial goals and start saving for them!"
                "saved_of" -> "saved of"
                "appearance" -> "Appearance"
                "dark_light_theme" -> "Dark/Light appearance"
                "language_currency" -> "Language & Currency"
                "monthly_limit" -> "Monthly Spending Limit"
                "limit_not_set" -> "Limit Not Set"
                "set_limit" -> "Set Limit"
                "custom_categories" -> "Custom Expense Categories"
                "add_custom_cat" -> "Add Custom Category"
                "cat_name" -> "Category Name"
                "color_selection" -> "Color selection:"
                "export_backup" -> "Export Data & Backups"
                "export_csv" -> "Export CSV"
                "import_csv" -> "Import CSV"
                "clear_data" -> "Clear All Data"
                "clear_data_prompt" -> "Clear All Data?"
                "clear_data_exp" -> "This will permanently delete all your records from Room database. Irreversible action. Continue?"
                "clear_data_confirm" -> "Yes, Clear All"
                "save" -> "Save"
                
                // Form Fields
                "edit_income" -> "Edit Income"
                "add_income" -> "Add Income"
                "edit_expense" -> "Edit Expense"
                "add_expense" -> "Add Expense"
                "edit_bill" -> "Edit Bill"
                "add_bill" -> "Add Recurring Bill"
                "add_goal" -> "Add Goal"
                "name" -> "Name / Description"
                "amount" -> "Amount"
                "category" -> "Category"
                "date" -> "Date (YYYY-MM-DD)"
                "notes_optional" -> "Notes (Optional)"
                "recurring_monthly" -> "Recurring Monthly"
                "frequency" -> "Frequency"
                "due_day_month" -> "Due Day of Month (Int)"
                "pick_color_theme" -> "Pick Color Theme"
                "pick_logo_icon" -> "Pick Logo Icon"
                "goal_name" -> "Goal Name"
                "target_amount" -> "Target Amount"
                "deadline" -> "Deadline (optional YYYY-MM-DD)"
                "saved_amount_status" -> "Saved: %s / %s"
                "log_savable_amount" -> "Log Savable Amount"
                "add_savings_btn" -> "Add Savings"
                "streak_days" -> "days streak"
                "streak_count" -> "d"
                
                else -> key
            }
        }
    }

    fun localizeCategory(category: String, isArabic: Boolean): String {
        if (!isArabic) return category
        return when (category.trim()) {
            // Income Categories
            "Salary" -> "المرتب الأسير 💵"
            "Freelance" -> "شغل حر ولقطات فري لانس 💻"
            "Investment" -> "أرباح البورصة والذهب 📈"
            "Rental" -> "إيجارات وعقارات 🏠"
            "Business" -> "شركتي ومشروعي الخاص 💼"
            "Bonus" -> "الحوافز والمكافآت 🎉"
            "Pension" -> "قبض المعاش 👵🏽"
            "Dividends" -> "عوائد وصناديق الاستثمار 💰"
            "Royalties" -> "حقوق وملكيات فكرية 📚"
            "Commission" -> "نسب وعمولات مبيعات 🤝"
            "Side Income" -> "سبوبة ومصالح جانبية ⚡"
            "Other" -> "شوية فلوس تانية 🪙"
            
            // Expense Categories
            "Food" -> "الأكل وطاقة البطن 🍔"
            "Transport" -> "مواصلات وأجرة وبنزين 🚗"
            "Housing" -> "إيجار وسكن كهربا ومياه 🏠"
            "Healthcare" -> "صيدلية وعلاج ودكتور 🏥"
            "Entertainment" -> "خروجات وعزومات وسفر 🎬"
            "Shopping" -> "هدوم ومشتريات شخصية 🛍️"
            "Utilities" -> "خدمات وطاقة وتليفونات ⚡"
            "Education" -> "مدرسة ودروس وكورسات 📚"
            "Health" -> "صيدلية وعلاج ودكتور 🏥"
            "Fun" -> "خروجات وعزومات وسفر 🎬"
            
            // Bill Categories
            "Internet" -> "اشتراك الإنترنت والواي فاي 🌐"
            "Phone" -> "فاتورة الموبايل والرصيد 📱"
            "Insurance" -> "تأمين وأقساط حماية 🛡️"
            "Streaming" -> "اشتراكات أفلام وموسيقى (نتفلكس وغيرها) 🍿"
            "Gym" -> "اشتراك الجيم واللياقة البدنية 🏋️"
            "Subscription" -> "اشتراكات دورية متنوعة ⚙️"
            "Savings" -> "تغذية حصالة التوفير 🏦"
            "Loan" -> "سداد قسط قرض أو جمعية 📉"
            "Tax" -> "ضرائب ورسوم حكومية 📄"
            
            "All" -> "كل الفئات"
            else -> category
        }
    }
}
